version: '3'

services:

  frontend:
    container_name: frontend
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    links:
      - app-dev
    command: "npm start"
    depends_on:
      - app-dev

  app-dev:
    container_name: app-dev
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./private.conf
    command: "nodemon app.js"
    depends_on:
      - database

  database:
    container_name: database
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db_volume:/data/db

volumes:
  db_volume:

networks:
  default:
    external:
      name: nginx-proxy
