version: '3'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/src
      - /src/node_modules
    expose:
        - 8080
    environment:
      - VIRTUAL_HOST=bmahlstedt.com,www.bmahlstedt.com
      - LETSENCRYPT_HOST=bmahlstedt.com
      - LETSENCRYPT_EMAIL=brian.mahlstedt@gmail.com
      - PORT=8080
    command: "npm start"

networks:
  default:
    external:
      name: nginx-proxy
