version: '3'

services:

  app-dev:
    container_name: app-dev
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ./server:/backend
      - /backend/node_modules
    ports:
      - 3000:3000
    command: "nodemon app.js"
    depends_on:
      - frontend
      - database

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    volumes:
      - ./client:/frontend
      - /frontend/node_modules
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
    command: "npm start"

  database:
    container_name: database
    image: mongo
    env_file:
      - ./docker/server/private.conf
    ports:
      - 27017:27017
    volumes:
      - db_volume:/data/db

volumes:
  db_volume:

networks:
  default:
    external:
      name: nginx-proxy
