version: '3'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/bmahlstedt
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=bmahlstedt.com,www.bmahlstedt.com
      - VIRTUAL_PROTO=uwsgi
    command: "uwsgi --ini ./docker/app/uwsgi.ini"

networks:
  default:
    external:
      name: nginx-proxy
