FROM node as build
WORKDIR /frontend
ENV PATH /frontend/node_modules/.bin:$PATH
COPY package.json /frontend/package.json
RUN npm install
COPY . /frontend
RUN npm run build

FROM node
COPY --from=build / /client/src/build
